apiVersion: v1
kind: Service
metadata:
  name: quote-backend
  namespace: quote-generator
  labels:
    app: quote-backend
spec:
  selector:
    app: quote-backend
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP
