apiVersion: v1
kind: Service
metadata:
  name: quote-frontend
  namespace: quote-generator
  labels:
    app: quote-frontend
spec:
  selector:
    app: quote-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  type: ClusterIP
